drop table if exists comments;
drop table if exists boards;
create table boards (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    content clob not null,
    created_at timestamp not null
);

create table comments (
    id bigint generated by default as identity primary key,
    board_id bigint not null,
    content varchar(2000) not null,
    created_at timestamp not null,
    constraint fk_comments_board foreign key (board_id) references boards(id) on delete cascade
);

